services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    platform: linux/arm64
    container_name: jenkins
    restart: unless-stopped
    group_add:
      - "991"
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
