pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh '''
                    POM_FILE=$(find . -name pom.xml -not -path "*/target/*" | head -n 1)
                    test -n "$POM_FILE"
                    mvn -f "$POM_FILE" clean compile
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    POM_FILE=$(find . -name pom.xml -not -path "*/target/*" | head -n 1)
                    test -n "$POM_FILE"
                    mvn -f "$POM_FILE" test
                '''
            }
        }
    }
}
