pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'docker run --rm -v "$PWD":/workspace -w /workspace/jenkins-cicd-project maven:3.9.9-eclipse-temurin-17 mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'docker run --rm -v "$PWD":/workspace -w /workspace/jenkins-cicd-project maven:3.9.9-eclipse-temurin-17 mvn test'
            }
        }
    }
}
